### ISSUE TITLE
Iterating over an empty table returns an empty entry.

### ISSUE THREAD

**Issue by Skrinikov** [rust-bpf/rust-bcc#100]
running `bpf_table.iter()` on an empty table returns an iterator with 1 entry. 

briefly answer these questions:

* what did you expect?
   * When I call `table.iter()` on an empty table, it should return an empty iterator
* what actually happened?
   * When I called `table.iter()` my loop ran once with an entry which was empty.
* what steps can we take to reproduce the behaviour you saw?
1. Create a BPF program with a table which is never updated. i.e. `BPF_HASH(table, u32)`
2. Try to iterate over that table in rust.

rust-bpf/bpf-tools#6

**Comment by brayniac** [comment]
I think this is fixed with #102. The additional smoketests are all passing too
