### ISSUE TITLE
Release for bcc 0.17.0 Support

### ISSUE THREAD

**Issue by hodgesds** [rust-bpf/rust-bcc#163]
Has a release been made for bcc 0.17.0 support yet? I saw #161 was merged recently, so it should be picked up in the next release.

**Comment by brayniac** [comment]
Not yet. Should be able to cut and publish a new release tomorrow.

**Comment by hodgesds** [comment]
Excellent! I've been using the repo directly and so far everything seems fine. Thanks again for maintaining this repo!

**Comment by brayniac** [comment]
Great! Glad to hear it's been working well for you. I'll update and close
this issue when the new release is on crates.io

**Comment by brayniac** [comment]
Version 0.0.30 is now published on crates.io
