### ISSUE TITLE
how about using template for replacing code in c file?

### ISSUE THREAD

**Issue by hsqStephenZhang** [rust-bpf/rust-bcc#182]
raw string raplace costs a lot, so i wonder if there is any better ways to minimize this kind of overhead

**Comment by brayniac** [comment]
Is there some prior art you can link to for alternative approaches? Is there some use-case where this overhead matters in practice?

**Comment by hsqStephenZhang** [comment]
I have read bcc tools's code, and found that it's almost based on text replacement. So instead of create a new String every step, why not using template engine to do the whole things for us? For example, https://github.com/sunng87/handlebars-rust can be a good way to solve this. Current approach is definitely sufficient though.

**Comment by brayniac** [comment]
I think this is probably out-of-scope for this library. It should be up to the users of this crate to determine how they wish to handle templating/substitution
