### ISSUE TITLE
IP reads in reverse order in some examples

### ISSUE THREAD

**Issue by enomado** [rust-bpf/rust-bcc#190]
Here https://github.com/rust-bpf/rust-bcc/blob/master/examples/tcpretrans.rs#L107

i noticed that it parses 11.249.50.92 instead of 92.50.249.11. 

Ipv4Addr::from(event.daddr.swap_bytes()) works.

thanks.

**Comment by brayniac** [comment]
Thanks for reporting this @enomado - a PR to fix would be welcome.

**Comment by Phoenix500526** [comment]
For my money, using from_be to change between host byte ordering and network byte ordering is a more generic way. I will make a PR to fix this issue.
