### ISSUE TITLE
unresolved imports `bcc::trace_parse`, `bcc::trace_read` no `trace_parse` in the root

### ISSUE THREAD

**Issue by Banyc** [rust-bpf/rust-bcc#193]
One line summary of the issue here

unresolved imports `bcc::trace_parse`, `bcc::trace_read`
no `trace_parse` in the root

briefly answer these questions:

* what did you expect? `bcc::trace_parse` can be accessed as `examples/hello_bpf.rs` did
* what actually happened? `bcc::trace_parse` cannot be accessed
* what steps can we take to reproduce the behaviour you saw? add dependency `bcc = "0.0.32"`, copy code from `examples/hello_bpf.rs` to `main.rs`, and run `cargo run`

**Comment by brayniac** [comment]
That example depends on functionality that is not published on crates.io yet. Will be fixed by the next release of this crate.
