### ISSUE TITLE
Unsound usages of unsafe implementation from `Vec<u8>` to `T`

### ISSUE THREAD

**Issue by llooFlashooll** [rust-bpf/rust-bcc#200]
Hi, I am scanning the bcc in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/core/mod.rs#L102
``` rust
// create a mutable pointer from a vector of bytes
fn null_or_mut_ptr<T>(s: &mut Vec<u8>) -> *mut T {
    if s.capacity() == 0 {
        ptr::null_mut()
    } else {
        s.as_mut_ptr() as *mut T
    }
}
```

This unsound implementation would create a misalignment issues if the type size of `Vec<u8>` is smaller than the type size of `T`.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences such as access out-of-bound. I am reporting this issue for your attention.

**Comment by brayniac** [comment]
Thanks for reporting this. As per the readme, this crate is not actively maintained and we recommend using libbpf-rs instead.

**Comment by llooFlashooll** [comment]
I see. Thanks for your kind response! Maybe I'll apply for the RustSec advisory id under its unmaintained category. This will help me validate the effectiveness of my tool. Thanks again!
