### ISSUE TITLE
How can I use two tables at the same time?

### ISSUE THREAD

**Issue by lilydjwg** [rust-bpf/rust-bcc#49]
`init_perf_map` returns a `PerfMap` that can be `poll`ed for data. But, what if I have two of them? E.g. in [tcprestrans](https://github.com/iovisor/bcc/blob/master/tools/tcpretrans.py) there is one for IPv4 and one for IPv6.

**Comment by brayniac** [comment]
Hi @lilydjwg - the tables are created and named in the bpf code you write. They can be accessed by that name with the usual `.table()` function from the userspace rust code. In the example you linked, look around https://github.com/iovisor/bcc/blob/master/tools/tcpretrans.py#L85 for where the tables are being created and https://github.com/iovisor/bcc/blob/master/tools/tcpretrans.py#L270 for where they're being accessed.

**Comment by lilydjwg** [comment]
Yes, I can have two tables. But which one should I `poll`?  In Python the `perf_buffer_poll` method is called on the shared `BPF` object, but in rust-bcc I get one `PerfMap` for each table and they have the `poll` method.

**Comment by brayniac** [comment]
@lilydjwg Ahh. I understand now. I'm honestly not sure for this right now. I haven't had any use-cases personally that wind up with a PerfMap. I'll have to do some more research and try to understand what the right thing would be here.

**Comment by ethercflow** [comment]
@brayniac @lilydjwg I made a PR to try to fix it.  PTAL.

**Comment by brayniac** [comment]
@lilydjwg - please re-open if necessary. I'll publish a new version with these changes shortly.

**Comment by lilydjwg** [comment]
It works for me, thanks!
