### ISSUE TITLE
Thoughts to supporting attach_xdp; attach_raw_socket? 

### ISSUE THREAD

**Issue by zeeshanlakhani** [rust-bpf/rust-bcc#65]
Checking-in on any discussion, thoughts to implementing the ability to attach via raw socket or attach xdp programs? I didn't see any related past issues, but was just wondering if there's been some attempts at implementing these previously?

If anything, it may be something we'd like to contribute upstream eventually as well. 

Thanks.

**Comment by brayniac** [comment]
Hi @zeeshanlakhani - to my knowledge, that hasn't been discussed or attempted as part of this project. I think we'd be open to PRs to add that functionality. Solid docs, tests, and examples will help make those PRs easier to review.

**Comment by rtkaratekid** [comment]
@zeeshanlakhani @brayniac has any work been done on this? If not, I may begin working on it.

**Comment by zeeshanlakhani** [comment]
@rtkaratekid we have not as of yet. We ended up leveraging bits of https://github.com/redsift/redbpf (for now) and writing our own loader for xdp programs. Would still love to see this happen more generally!

**Comment by jbpratt78** [comment]
Hi @brayniac , along the same lines as this issue, what are your thoughts on an implementation of [get_syscall_fnname](https://github.com/iovisor/bcc/blob/ab54de2e4449027f2b4dccd022adc57bec4fd4eb/src/python/bcc/__init__.py#L632) to go along with the use of [ksysname](https://docs.rs/bcc/0.0.17/bcc/core/struct.BPF.html#method.ksymname)? Or is there a way that is currently working around this? Thank you and sorry for my lack of knowledge.

**Comment by brayniac** [comment]
@jbpratt78 - this is probably best for a new issue.

**Comment by brayniac** [comment]
Just to update here, 0.0.27 now has XDP support.

**Comment by brayniac** [comment]
Marking as 'help wanted' for attach_raw_socket

**Comment by brayniac** [comment]
I think this is fully addressed now. Closing
