### ISSUE TITLE
Would it be okay to submit a partial implementation of tcpconnect.py ?

### ISSUE THREAD

**Issue by afbase** [rust-bpf/rust-bcc#78]
Hi,

I'm working on an attempt to recreate [tcpconnect.py](https://github.com/iovisor/bcc/blob/master/tools/tcpconnect.py).  In part this is to help me teach myself rust and eBPF at the same time.  

The "count" mode is something I'm having a bit of difficulty porting at the moment but I can get the other functionality of tcpconnect working.  

Would rust-bcc accept partial implementations?

**Comment by afbase** [comment]
I would add the question label to this but I can't seem to do that.

**Comment by brayniac** [comment]
@afbase - That's an excellent question!

Historically, we've been adding new examples more to test particular functionality. For example, when raw_tracepoint support was added, we added an example that we could then run in CI. I don't think we have a goal to mirror the full set of tools and functionality from the bcc repo. As such, the current examples are not strictly functionally equivalent.

I'd prefer new examples be added for similar reasons, to serve as a demo and a smoke test. `iovisor/bcc/tools` is quite massive. If we do want to provide Rust alternatives to those tools, I'd rather have that development happen in a separate repo (eg `rust-bpf/tools`). There, the standards should be higher, as the intent would be to provide useful tools. 

The benefit to developing those in a separate repo would be that necessary maintenance on those tools could be deferred, allowing us to maintain development speed on this library without the burden of needing to make immediate changes to those tools. 

@jvns - do you have thoughts on this?

**Comment by afbase** [comment]
>I'd prefer new examples be added for similar reasons, to serve as a demo and a smoke test. iovisor/bcc/tools is quite massive. If we do want to provide Rust alternatives to those tools, I'd rather have that development happen in a separate repo (eg rust-bpf/tools)

I can definitely see how a separate repository can be helpful here.  The "how I see value" in a separate repo are:

1. **Explanation of Example/Tool Purpose**: Charter that the repository tools and examples primary objective could test functionality of `rust-bcc` and then secondarily provide utility in other use cases.
1. **Tool Utilities Commonality**: Common set of utilities for handling data across a set of examples. Perhaps this is a facet of higher standards for examples. It would be a bit unwieldy to see  each example/tool with their own set of data exporting or presentation - which leads to my next point.
1. **Versatile Presentation of Information**: Tools supporting multiple use cases.  You mention demo and smoke testing as use cases; another use case I see is presenting the ebpf data for various monitoring/logging services (e.g. CLI, prometheus, fluentd, ELK, gRPC, etc.) to consume, that way many environments can support utilizing these tools right away.

**Comment by brayniac** [comment]
@afbase I think I mostly agree with 1 & 2. I'd leave some testing-purpose examples here in rust-bcc, but would want things in the proposed `rust-bpf/tools` repo to be more polished. There's some ways I believe we could improve on the existing python bcc tools, particularly in being able to produce static binaries of our tools. Makes it a lot easier to run in real-world environments.

For 3 - I'd actually plug my work project: https://github.com/twitter/rezolus

A full telemetry agent is a fairly involved thing which I see as separate from ad-hoc tools. If your interest is in eventually producing telemetry with eBPF, I encourage you to take a look at that project.

If we'd still like, I can create a `rust-bpf/tools` repo. 

Again, @jvns - let me know what you think

**Comment by jvns** [comment]
Making a `rust-bpf/tools` project sounds great! I've thought before that because Rust is faster than Python it might be possible to build more powerful BPF tools in Rust (the reason I started this library in the first place was to [profile & aggregate Ruby memory allocations](https://jvns.ca/blog/2018/01/31/spying-on-a-ruby-process-s-memory-allocations/)). 

> The benefit to developing those in a separate repo would be that necessary maintenance on those tools could be deferred, allowing us to maintain development speed on this library without the burden of needing to make immediate changes to those tools.

This makes sense to me.

**Comment by brayniac** [comment]
@jvns I created it as https://github.com/rust-bpf/ebpf-tools - if we really want it to just be "tools", happy to rename - but if we're publishing to crates.io `cargo install ebpf-tools` makes more sense to me? I guess technically the crate name and repo name don't need to match. LMK if you have any opinion on that. I pushed some initial content to kick it off.

**Comment by afbase** [comment]
Thank you for your responses!  I hope to make PRs soon into ebpf-tools. :-)

**Comment by brayniac** [comment]
Just to note, I recently learned the current preference is to refer to it as "BPF" not "eBPF" so the tools repo has been renamed accordingly. https://github.com/rust-bpf/bpf-tools is the new repo, just in-case the redirect stops working at some point
