### ISSUE TITLE
Support for pre-compiled .elf BPF binaries?

### ISSUE THREAD

**Issue by rtkaratekid** [rust-bpf/rust-bcc#82]
One line summary of the issue here
Looking for functionality to attach probes with pre-compiled .elf files.

---

I've been looking through the repo, and I'm not sure if this feature is supported (being a newcomer to Rust). But I'm looking to take pre-compiled BPF binaries in the form of ".o" or ".elf" or whatever and attach the probes without compiling. I'm looking at steps like these:
```Rust
let mut module = BPF::new(code)?;
let uprobe_code = module.load_uprobe("count")?;
module.attach_uprobe(
    "/lib/x86_64-linux-gnu/libc.so.6",
    "strlen",
     uprobe_code,
     -1, /* all PIDs */
)?;
```
And am wondering if said .elf file could be substituted for `uprobe_code`.

If it doesn't have this functionality, I'd have to poke around the library a bit more first (and brush up a bit more on my Rust), but I might be willing to develop that if it doesn't seem like it would conflict with the overall project. Otherwise I may make a fork just for that specific use-case.

Thanks for the work you've done!

**Comment by rsdy** [comment]
You might want to take a look at using [ingraind](https://github.com/redsift/ingraind), or the library [redbpf](https://github.com/redsift/redbpf) for this kind of thing. The `cargo-bpf` package also provides a toolchain to write/build probes in Rust and load the elf binaries using the `cargo bpf load`.

**Comment by rtkaratekid** [comment]
I was actually looking at your repo as well and noticed no uprobes. Is that just a lack of priority or is it more difficult than kprobes etc? Also, I wasn't able to get the example in the `cargo-bpf` doc page to compile, but maybe I should start a discussion over there if we're going to start talking about another repo.

**Comment by rsdy** [comment]
@rtkaratekid definitely do open an issue. I don't think it will be too difficult to add support for uprobes, but it's not been my focus. I will have some time to look at it next week.
