### ISSUE TITLE
Possibility to support `get_syscall_fnname`

### ISSUE THREAD

**Issue by jbpratt78** [rust-bpf/rust-bcc#86]
Thought on an implementation of [get_syscall_fnname](https://github.com/iovisor/bcc/blob/ab54de2e4449027f2b4dccd022adc57bec4fd4eb/src/python/bcc/__init__.py#L632) to go along with the use of [ksysname](https://docs.rs/bcc/0.0.17/bcc/core/struct.BPF.html#method.ksymname)? Or is there a way that is currently working around this? Thank you and sorry for my lack of knowledge.

https://github.com/iovisor/bcc/blob/master/tools/statsnoop.py#L116

**Comment by brayniac** [comment]
#87 has landed which resolves this.
